var scriptVersion = "0.0.4",
  mechanics_button_url =
    "https://lh3.googleusercontent.com/fife/AKsag4O5APaNGjvOuSuIshgutY5rR1elxX_4VGDNrXQ89qWu56LFVord8gF-o_5X_nzEezlWFR67DKgBmTOdxde_h5QISv-LiQxaAs0Nvpm2LJXl_U1VCxBQk2SVtQgYD3Snzf2EgKBLLYbTOQSU5As1RVo9XzlSfzqTER08otSR8pC1tgNULeTqdUtNv7v2GB8gKP21QIMK67K-GjQZzSSJMNH8LVStCt4mD3PtYGnZ93LlNVx25O_BjQ_AXPNmwJiFzClJs4QtvUu4CscPXN12raefpyYUaBCWpZ3WTTtHMDQ_ffPLZ-T2W5Cvq3AMI2bBIB2IxwH397ePuO2kn2LEfptrUiWljb5iy17kPgzbFZn-lz_Gb_M8OJ6zldCIx4T5cP7PocL6yqriNhKp_n4JnnOYnQKloeBxRyA30oFViGTDdkXLV66mehmXyswAgv8gMbpbafP_WS550mECrl5ku9RZIf8-W00IDnaqK6ipcoHQVryd46tUcGSJl2B_9MbUxpchcD2UW4xyxWiV2Bj6cHRAVJa6jcQpgRKssq_hSUMTsQTASFM9yW_FxhcWDU78kMYRaBWhu1evNppJJd1vaQDSoh3NwtcO11pJN3iUy6UsYouBT429VLQcDkepwi0ZF1S-o2GRe8NgRZzTHhpwpwi_uHL_pZBwaKFww6VzvPPs9yDetb-TB6YddhjTTTkFNjmNhE5GEwHkJdAE2QLotdZMrSuB1FcDL_w3K2fO5KkSIY4JTDpKA3Ov3R2y62ha9RWhDG5RQxZRYtmnKbagS5a1vPaP3hTvh0OGpwK-_9CHhkDrjUBlXOkZQOxS7drbLu4B2XtsZZDbSP7GDyp56Y1KQgWaYGY6yLiArOFU1VKki13hsop_bDz_CjV6LL_JFBq-9ApybnTPrHxDso_DKimaN9BbaXEEdDbneujn1TwMB75IoEneFnlh7f-PbxceE7TEV-pGT5uinYBIcgj_vNnPQgEgygtO8QLx2mgeFOwgDMfH9W610tCyQT5_92ByYVbkPFBpEMU4sEr38U-kj-E9PQ8SuCeDwCdAptSUjT2msmtJerhBlnxm7rpmHlOEP5gmrU8VdM9A1kTGCP3syMl_iZArCHqyTLe8vftzr5sSxW0N4d-drJ7YbVji87jrX7v8D05VT1ccOIEJMJVzU8t4k_RhWl5wz3fDboycFZtpdl-Q47N5TNcIzBmEPemPr9baiRu7cDnhXTyW4sxeANsCBu7-5WiIkMwEz20P_Rs40zMQLIlICFUGqXRjvGLXvCw-JeV5YLolXSkHYq9Z_AhlqsTvfJXThodX-JZdNSJXUGV2zu2aWEDfKwHel-yIbt6ItYua9kwe9OtUfHPoNsbjUSSTHEMv9fU7HYqIFlpbxbcS8axQczaf_7IlLvU5jr8ZznYEPtbGeH89w8Tx76jg7QDKh6dCaS6UCgdlIfZCy90Tlz5wyNQj8HubMLYv9o1eSXsQN9OxykybnCXOa6se6HIvCaj81gqeSFDQ55kO-Fbz7965CturGud-ivOb0Ib6FFj6Ff0yQiPRZzZr9rUlhwgGTPNCZS3EdcoliUqkRw=w2505-h1337",
  ss = SpreadsheetApp.getActiveSpreadsheet(),
  settingsSheet = ss.getSheetByName("Settings"),
  logSheet = ss.getSheetByName("Logs"),
  staticSheet = ss.getSheetByName("Setup und Co"),
  statisticsSheet = ss.getSheetByName("Statistics"),
  downtimeSheet = ss.getSheetByName("Up-/Downtime"),
  // Colors
  lightGray = "#efefef",
  gray = "#ABABAB",
  red = "#FF0000",
  green = "#008B00",
  yellow = "#FFFF00",
  black = "#000000",
  // Mechanics to calculate in Logs per Boss
  basicMechanics = ["Downed", "Dead", "Got up", "Res"],
  vgMechanics = ["Boss TP", "Seeker", "Floor dmg"],
  gorseMechanics = ["Slam", "Egged", "Black Goo"],
  sabMechanics = [
    "Shell-Shocked",
    "Timed Bomb",
    "Flak Shot",
    "Cannon Shot",
    "Flamethrower (Karde)",
    "Bandit Kick",
  ],
  slothMechanics = [
    "Tantrum",
    "Poison (Action Key)",
    "Flame Breath",
    "Shake",
    "Toxic Floor",
  ],
  mattMechanics = [
    "Rapid Fire",
    "Reflected Rapid Fire",
    "Jump Shards",
    "Tornado",
    "Storm cloud",
    "Well",
    "Stood in Well",
    "Corruption",
    "Corruption dmg",
    "Sacrifice",
    "Bomb",
    "Spirit hit",
  ],
  kcMechanics = ["Fixated", "Debris", "Phantasmal Blades", "Tower Drop"],
  xeraMechanics = ["Red Orb", "Orb AoE", "Shield", "TP"],
  cairnMechanics = ["Orange TP", "Green (lift)", "Shared Agony"],
  moMechanics = ["Jade Aura", "Jade Explosion"],
  samMechanics = [
    "Shockwave",
    "Sweep",
    "Slam",
    "Fixate: Samarog",
    "Big Green",
    "Small Green",
    "Failed Green",
    "Spear Aoe",
    "Spear Spawned",
    "Brutalized",
  ],
  deiMechanics = [
    "Black Oil",
    "Black Oil Trigger",
    "Boss Smash",
    "Tear",
    "Mind Crush",
    "Chosen (Green)",
  ],
  shMechanics = [
    "Inner Donut",
    "Outer Donut",
    "Golem Aoe",
    "4 Slices 1",
    "4 Slices 2",
    "Scythe",
    "8 Slices",
    "Torment+Poison Spin",
    "Wurm Spit",
  ],
  rrMechanics = ["Hit by Bomb", "Stun Bomb"],
  bkMechanics = ["Cone Auto Attack", "Cracks", "Green Stack"],
  dhuumMechanics = [
    "Golem Dmg",
    "Bomb",
    "Shackles",
    "Shackles Dmg",
    "Cracks",
    "Suck dmg",
    "Dip AoE",
  ],
  caMechanics = [
    "Arm Slam",
    "Purple Balls",
    "Junk Fall",
    "Ruptured Ground",
    "Near Arm Slam",
  ],
  twinsMechanics = [
    "Waterlogged",
    "Vapor Rush Charge",
    "Tidal Pool",
    "Shockwave",
    "Launch Field",
    "Water Poison",
    "Float Bubble",
    "Tornado",
    "Boon Steal",
    "Cyclone Burst",
  ],
  qadimMechanics = [
    "Fire on Lines",
    "Flame Bolt Stun",
    "KB Push",
    "Mace Shockwave",
    "Mace Impact",
    "Inferno Pool",
    "KB/Pin down",
    "Tail Swipe",
    "Fire Breath",
    "Wing Buffet",
    "Qadim Hitbox AoE",
    "Reaper Claw",
    "Port to Qadim",
  ],
  adinaMechanics = ["Radiant Blindness", "Mines"],
  sabirMechanics = ["Arena AoE hit", "Pushed"],
  qpeerMechanics = [
    "Pylon Magma",
    "Energized Affliction",
    "Shockwave Push",
    "Dome Knockback",
    "Pattern Energy Hit",
    "Lightning Hit",
    "Small Lightning Hit",
    "Magma Field",
    "Qadim Rush",
    "Aimed Projectile",
    "Bad Tether",
  ],
  trinMechanics = [
    "Cone",
    "Side Cone",
    "Shockwave",
    "Puddle",
    "Exposed Applied",
    "Green",
    "Green Debuff",
    "Bomb",
  ],
  ankkaMechanics = [
    "Hands Hit",
    "Death's Embrace Hit",
    "Death's Hand Spread",
    "Death's Hand Hit (placeable)",
    "Death's Hand Hit (transitions)",
    "Krait Hit",
    "Quaggan Hit",
    "Zhaitan's Reach Pull",
    "Zhaitan's Reach Knock",
    "Imminent Death Hit",
    "Imminent Death Buff",
    "Devouring Void Applied",
    "Hallucinations Debuff",
    "Lich Fixation",
    "Fixated Hatred",
  ],
  koMechanics = [
    "Exposed",
    "Debilitated",
    "Infirmity",
    "Wave Hit",
    "Burst Hit",
    "Rush Hit",
    "Stood in Flames",
    "Explosive Uppercut Hit",
  ],
  olcMechanics = [
    "Boiling Aether Hit (Vermilion & Indigo)",
    "Boiling Aether Hit (Arsenite)",
    "Dual Horizon Hit",
    "Tri Bolt Hit",
    "Tribocharge Hit",
    "Noxious Vapor Blade Hit",
    "Noxious Return Hit",
    "Tidal Torment Applied",
    "Ergo Shear Applied",
    "Exposed Applied",
    "Spaghettification Hit",
    "Fixated Applied",
    "Thundering Ultimatum Hit",
  ],
  coMechanics = [
    "Debilitated Applied",
    "Infirmity",
    "Spinning Nebula Hit",
    "Demonic Blast Hit",
    "Soul Feast Hit",
    "Planet Crash Projectiles Hit",
    "Charging Constellation Hit",
    "Targetted by Shooting Stars",
    "Residual Anxiety",
    "Lost Control",
    "Targetted by Soul Feast",
    "Shared Destruction Target (Green - Meteor Crash)",
    "Target Order Apllication",
    "Extreme Vulnerability Application",
    "Demonic Aura Stacks Removed",
    "Casted Purifying Light",
    "Purifying Light Hit Dagda"
  ],
  tofMechanics = [
    "Exposed Applied",
    "Insatiable Application",
    "Crushing Regret Hit",
    "Empowered Chrushing Regret Hit",
    "Crushing Regret Application",
    "Wail of Despair Hit",
    "Empowered Wail of Despair Hit",
    "Pool of Despair Hit",
    "Empowered Pool of Despair Hit",
    "Envious Gaze Hit",
    "Empowered Envious Gaze Hit",
    "Malicious Intent Hit",
    "Targetted by Malicious Intent",
  ];
